# Generated by Django 5.2.4 on 2025-08-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrecord',
            name='employee',
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('overdue', 'Overdue')], max_length=50),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='employee',
            field=models.ManyToManyField(to='system.employee'),
        ),
    ]
