# Generated by Django 4.2.22 on 2025-08-04 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_initial'),
        ('system', '0002_remove_trainingrecord_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Audit', 'verbose_name_plural': 'Audits'},
        ),
        migrations.AlterModelOptions(
            name='capa',
            options={'ordering': ['-due_date'], 'verbose_name': 'CAPA', 'verbose_name_plural': 'CAPAs'},
        ),
        migrations.AlterModelOptions(
            name='changecontrol',
            options={'ordering': ['-created_at'], 'verbose_name': 'Change Control', 'verbose_name_plural': 'Change Controls'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='nonconformance',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Non-Conformance', 'verbose_name_plural': 'Non-Conformances'},
        ),
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Risk Assessment', 'verbose_name_plural': 'Risk Assessments'},
        ),
        migrations.AlterModelOptions(
            name='trainingrecord',
            options={'ordering': ['-completion_date'], 'verbose_name': 'Training Record', 'verbose_name_plural': 'Training Records'},
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='employee',
        ),
        migrations.AddField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='capa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changecontrol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='employees',
            field=models.ManyToManyField(related_name='training_records', to='system.employee'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External'), ('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Other', 'Other')], default='Internal', max_length=100),
        ),
        migrations.AlterField(
            model_name='audit',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audit',
            name='findings',
            field=models.TextField(blank=True, verbose_name='Audit Findings'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='account.organisation'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='capa',
            name='issue',
            field=models.TextField(verbose_name='Issue Description'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='account.organisation'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_capas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capa',
            name='root_cause',
            field=models.TextField(verbose_name='Root Cause'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Verified', 'Verified'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='change_description',
            field=models.TextField(verbose_name='Description of the Change'),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='impact_analysis',
            field=models.TextField(verbose_name='Impact Analysis'),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_controls', to='account.organisation'),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='account.organisation'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Archived', 'Archived'), ('Rejected', 'Rejected')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='account.organisation'),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformances', to='account.organisation'),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_non_conformances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='source',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=100),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='identified_risks',
            field=models.TextField(verbose_name='Identified Risks'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='impact',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=100),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='account.organisation'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_type',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Financial', 'Financial'), ('Compliance', 'Compliance'), ('Strategic', 'Strategic'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Monitoring', 'Monitoring'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='account.organisation'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('overdue', 'Overdue')], default='in_progress', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('organisation', 'title', 'version')},
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
