# Generated by Django 4.2.22 on 2025-08-04 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0003_alter_audit_options_alter_capa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('approval_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_policies', to='account.organisation')),
            ],
            options={
                'verbose_name': 'Quality Policy',
                'verbose_name_plural': 'Quality Policies',
                'ordering': ['-approval_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('agenda', models.TextField()),
                ('minutes', models.TextField()),
                ('actions', models.TextField()),
                ('attendees', models.ManyToManyField(related_name='review_attendance', to='system.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_reviews', to='account.organisation')),
            ],
            options={
                'verbose_name': 'Management Review',
                'verbose_name_plural': 'Management Reviews',
                'ordering': ['-date'],
            },
        ),
    ]
