# Generated by Django 4.2.22 on 2025-08-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_plan_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
